Bail out if the build fails
Signed-off-by: Bryan Hundven <bryanhundven@gmail.com>

diff --git a/acidify b/acidify
--- a/acidify
+++ b/acidify
@@ -318,6 +318,9 @@ function build()
     fi
 
     mka "$build_argument"
+    if [ ! $? -eq 0 ]; then
+        error "mka ${build_argument} failed!\n"
+    fi
 }
 
 function clean()
